### PR TITLE
srv1 implementation v1

### PR DESCRIPTION
**Pull request by azopat**

### CODE REVIEW

**Comment by mahnouman** [comment]
Hello, please submit a proper readme file along with the code, thank you

**Comment by mahnouman** [comment]
Hello @azopat ,, please:
- [ ] Fix the conflict.
- [ ] Detail the first paragraph by explaining that this is a service of the main repo (go-k8s-infra) and link to it.
- [ ] Use Go version 1.16 and reference that in the files, unless there is a reason please state the reason.
- [ ] Please detail the steps of how to build the Docker image. So it would be steps to follow.
- [ ] Please mention other Docker and Kubernetes commands that would be frequently used while developing, like stopping docker, rebuilding and similar for Kubernetes.
- [ ] Please mention testing steps for this particular code, the steps mentioned for the overall setup (i.e. the one for processing the files) can be moved to the infra repo.
- [ ] Please mention how to check logs.
- [ ] Please reference the updated diagram from the infra repo.

**Comment by azopat** [comment]
@mahnouman  it's done

**Comment by mahnouman** [comment]
Hello @azopat 
- [ ] Please do not remove the badges section of the readme file.
- [ ] First make sure that you have rabbitmq and minio running, then run the command bellow ,, where to get those from, please refer to or add steps.
- [ ] In main.go processing_exchange   = "processing-exchange" ,,, what is the processing-exchange queue, does it have a different name in the diagram, if so please use that name or we need to append it, please provide details.
- [ ] In go.mod your own fork is being references, please fix this: 	github.com/azopat/k8-go-comm v1.1.2-0.20210225022620-7a8a1c8a75cc

**Comment by azopat** [comment]
processing-exchange is not the queue name, it's the exchange name. Queue name is as on the image.
Others are done except rabbitmq which will be done when we push code to https://github.com/k8-proxy/go-k8s-srv1/pull/2

**Pull request merged**
